[build-system]
requires = ["setuptools>=61.0"]
build-backend = "setuptools.build_meta"

[project]
name = "pypsucurvetrace"
version = "0.0.1"
authors = [
  { name="Matthias Brennwald", email="mbrennwa@gmail.com" },
]
description = "A software toolbox for I/V curve tracing of electronic devices using programmable power supplies (PSUs)."
readme = "README.md"
requires-python = ">=3.7"
dependencies = [
    "minimalmodbus",
    "simple_pid",
    "pydigitemp",
    "matplotlib"
]
classifiers = [
    "Programming Language :: Python :: 3",
    "License = GPL-3.0-or-later",
    "Operating System :: OS Independent",
]

[project.scripts]
# as defined in src/pypsucurvetrace/__init__.py
curvetrace   = "PyPSUcurvetrace:curvetrace"
curveplot    = "PyPSUcurvetrace:curveplot"
curveprocess = "PyPSUcurvetrace:cprocess"

[project.urls]
"Homepage" = "https://github.com/mbrennwa/PyPSUcurvetrace"
"Bug Tracker" = "https://github.com/mbrennwa/PyPSUcurvetrace/issues"
